# Generated by Django 5.0.4 on 2024-05-03 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clase', '0002_comision'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clase.curso'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='nombre',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
